# Generated by Django 4.1.7 on 2023-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
