# Generated by Django 4.1.7 on 2023-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="user", name="phone", field=models.IntegerField(null=True),
        ),
    ]
