# Generated by Django 4.1.7 on 2023-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_bids_bids_alter_bids_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bids",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
