# Generated by Django 4.1.7 on 2023-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_bids_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bids",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=5, null=True
            ),
        ),
    ]
