# Generated by Django 4.1.7 on 2023-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_bids_bids"),
    ]

    operations = [
        migrations.RemoveField(model_name="watchlist", name="products",),
        migrations.AddField(
            model_name="watchlist",
            name="products",
            field=models.ManyToManyField(
                related_name="mera_saman", to="auctions.listings"
            ),
        ),
    ]
