# Generated by Django 4.1.7 on 2023-04-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_remove_watchlist_products_watchlist_products"),
    ]

    operations = [
        migrations.RemoveField(model_name="watchlist", name="products",),
        migrations.AddField(
            model_name="watchlist",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mera_saman",
                to="auctions.listings",
            ),
        ),
    ]
