# Generated by Django 4.1.7 on 2023-04-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_remove_watchlist_products_watchlist_products"),
    ]

    operations = [
        migrations.AlterModelOptions(name="bids", options={"get_latest_by": "bids"},),
    ]
