# Generated by Django 4.1.7 on 2023-04-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_bids_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
