# Generated by Django 4.1.7 on 2023-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="product",
            field=models.CharField(max_length=265, null=True),
        ),
    ]
