# Generated by Django 4.1.7 on 2023-04-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_items_sold_to_listings_sold_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mera_saman",
                to="auctions.items",
            ),
        ),
    ]
