# Generated by Django 4.1.7 on 2023-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
